apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s

  - name: Redis
    type: redis
    access: proxy
    url: redis:6379
    isDefault: false
    editable: true
    jsonData:
      client: standalone
      pingInterval: 10s
      poolSize: 5
